### ISSUE TITLE
TypeError occured when running the example code

### ISSUE THREAD

**Issue by qy201706** [olbapjose/pyspark-approx-smote#10]
I appreciate your meaningful work which can help me apply SMOTE in the Pyspark framework. Unfortunately, I got some errors when running the example code. Could you please help me fix it? Thank you very much.

The whole Traceback is following:

> Traceback (most recent call last):
  File "/home/up2242285/Mini_Project/Spark_hdfs_RF.py", line 67, in <module>
       seed=1234
  File "/home/anaconda3/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/__init__.py", line 110, in wrapper
  File "/home/up2242285/Mini_Project/pyspark-approx-smote/pyspark_approx_smote/asmote.py", line 89, in __init__
       self._java_obj = self._new_java_obj("org.apache.spark.ml.instance.ASMOTE", self.uid)
  File "/home/anaconda3/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 67, in _new_java_obj
TypeError: 'JavaPackage' object is not callable

**Comment by qy201706** [comment]
The env is:
<img width="463" alt="image" src="https://github.com/olbapjose/pyspark-approx-smote/assets/39509371/6be47225-0c5a-4a63-afd0-46f7a3a44eac">

**Comment by olbapjose** [comment]
@qy201706  Hi, thanks for your commet. Actually I did not develop this code but just forked another repository which I cannot find right now. Just to check, have you included the JAVA dependency? Remember this is just a wrapper thar requires to include the true parallel implementation developed in Java in https://github.com/mjuez/approx-smote
